In [38]:
import geopandas as gpd
import pandas as pd
import json

In [8]:
geoshape = gpd.read_file('/Users/rodolfodom/Downloads/stcmetro_shp/STC_Metro_estaciones_utm14n.shp')

In [9]:
geoshape.shape

(195, 10)

In [10]:
geoshape

,SISTEMA,NOMBRE,LINEA,EST,CVE_EST,CVE_EOD17,TIPO,ALCALDIAS,AÑO,geometry
0,STC Metro,Pantitlán,01,01,STC0101,05014,Terminal / Transbordo,Venustiano Carranza,1984,POINT Z (-99.07474 19.41633 0.00000)
1,STC Metro,Zaragoza,01,02,STC0102,05020,Intermedia,Venustiano Carranza,1969,POINT Z (-99.08229 19.41192 0.00000)
2,STC Metro,Gomez Farías,01,03,STC0103,05007,Intermedia,Venustiano Carranza,1969,POINT Z (-99.09021 19.41648 0.00000)
3,STC Metro,Boulevard Puerto Aéreo,01,04,STC0104,05003,Intermedia,Venustiano Carranza,1969,POINT Z (-99.09626 19.41994 0.00000)
4,STC Metro,Balbuena,01,05,STC0105,05001,Intermedia,Venustiano Carranza,1969,POINT Z (-99.10277 19.42336 0.00000)
...,...,...,...,...,...,...,...,...,...,...
190,STC Metro,Múzquiz,B,17,STCLB17,05185,Intermedia,Estado de México - Ecatepec,2000,POINT Z (-99.04207 19.50149 0.00000)
191,STC Metro,Ecatepec,B,18,STCLB18,05179,Intermedia,Estado de México - Ecatepec,2000,POINT Z (-99.03607 19.51513 0.00000)
192,STC Metro,Olímpica,B,19,STCLB19,05188,Intermedia,Estado de México - Ecatepec,2000,POINT Z (-99.03334 19.52134 0.00000)
193,STC Metro,Plaza Aragón,B,20,STCLB20,05189,Intermedia,Estado de México - Ecatepec,2000,POINT Z (-99.03018 19.52848 0.00000)
194,STC Metro,Ciudad Azteca,B,21,STCLB21,05177,Terminal,Estado de México - Ecatepec,2000,POINT Z (-99.02751 19.53451 0.00000)

In [11]:
geoData = geoshape[['NOMBRE', 'LINEA', 'geometry']]
geoData

                     NOMBRE LINEA                              geometry
0                 Pantitlán    01  POINT Z (-99.07474 19.41633 0.00000)
1                  Zaragoza    01  POINT Z (-99.08229 19.41192 0.00000)
2              Gomez Farías    01  POINT Z (-99.09021 19.41648 0.00000)
3    Boulevard Puerto Aéreo    01  POINT Z (-99.09626 19.41994 0.00000)
4                  Balbuena    01  POINT Z (-99.10277 19.42336 0.00000)
..                      ...   ...                                   ...
190                 Múzquiz     B  POINT Z (-99.04207 19.50149 0.00000)
191                Ecatepec     B  POINT Z (-99.03607 19.51513 0.00000)
192                Olímpica     B  POINT Z (-99.03334 19.52134 0.00000)
193            Plaza Aragón     B  POINT Z (-99.03018 19.52848 0.00000)
194           Ciudad Azteca     B  POINT Z (-99.02751 19.53451 0.00000)

[195 rows x 3 columns]

In [23]:
duplicated_names = geoData[geoData['NOMBRE'].duplicated()]["NOMBRE"].unique()
duplicated_names

array(['Pino Suárez', 'Hidalgo', 'Balderas', 'Candelaria', 'La Raza',
       'Consulado', 'Pantitlán', 'Instituto del Petróleo',
       'Deportivo 18 de Marzo', 'Martín Carrera', 'El Rosario', 'Tacuba',
       'Tacubaya', 'Bellas Artes', 'Salto del Agua', 'Chabacano',
       'Santa Anita', 'Jamaica', 'Centro Médico', 'Atlalilco', 'Ermita',
       'Zapata', 'Mixcoac', 'Guerrero', 'Garibaldi/Lagunilla', 'Morelos',
       'San Lázaro', 'Oceanía'], dtype=object)

In [27]:
geoData.loc[geoData['NOMBRE'].isin(duplicated_names), 'NOMBRE'] = geoData['NOMBRE'] + '-' + geoData['LINEA']

In [28]:
geoData

                     NOMBRE LINEA                              geometry
0              Pantitlán-01    01  POINT Z (-99.07474 19.41633 0.00000)
1                  Zaragoza    01  POINT Z (-99.08229 19.41192 0.00000)
2              Gomez Farías    01  POINT Z (-99.09021 19.41648 0.00000)
3    Boulevard Puerto Aéreo    01  POINT Z (-99.09626 19.41994 0.00000)
4                  Balbuena    01  POINT Z (-99.10277 19.42336 0.00000)
..                      ...   ...                                   ...
190                 Múzquiz     B  POINT Z (-99.04207 19.50149 0.00000)
191                Ecatepec     B  POINT Z (-99.03607 19.51513 0.00000)
192                Olímpica     B  POINT Z (-99.03334 19.52134 0.00000)
193            Plaza Aragón     B  POINT Z (-99.03018 19.52848 0.00000)
194           Ciudad Azteca     B  POINT Z (-99.02751 19.53451 0.00000)

[195 rows x 3 columns]

In [29]:
geoData["NOMBRE"] = geoData["NOMBRE"].str.replace("-0", "-")
geoData

/opt/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

                     NOMBRE LINEA                              geometry
0               Pantitlán-1    01  POINT Z (-99.07474 19.41633 0.00000)
1                  Zaragoza    01  POINT Z (-99.08229 19.41192 0.00000)
2              Gomez Farías    01  POINT Z (-99.09021 19.41648 0.00000)
3    Boulevard Puerto Aéreo    01  POINT Z (-99.09626 19.41994 0.00000)
4                  Balbuena    01  POINT Z (-99.10277 19.42336 0.00000)
..                      ...   ...                                   ...
190                 Múzquiz     B  POINT Z (-99.04207 19.50149 0.00000)
191                Ecatepec     B  POINT Z (-99.03607 19.51513 0.00000)
192                Olímpica     B  POINT Z (-99.03334 19.52134 0.00000)
193            Plaza Aragón     B  POINT Z (-99.03018 19.52848 0.00000)
194           Ciudad Azteca     B  POINT Z (-99.02751 19.53451 0.00000)

[195 rows x 3 columns]

In [30]:
geoData["lat"] = geoData.geometry.y
geoData["lon"] = geoData.geometry.x
geoData

/opt/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/opt/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,NOMBRE,LINEA,geometry,lat,lon
0,Pantitlán-1,01,POINT Z (-99.07474 19.41633 0.00000),19.416334,-99.074736
1,Zaragoza,01,POINT Z (-99.08229 19.41192 0.00000),19.411920,-99.082289
2,Gomez Farías,01,POINT Z (-99.09021 19.41648 0.00000),19.416478,-99.090210
3,Boulevard Puerto Aéreo,01,POINT Z (-99.09626 19.41994 0.00000),19.419942,-99.096259
4,Balbuena,01,POINT Z (-99.10277 19.42336 0.00000),19.423355,-99.102774
...,...,...,...,...,...
190,Múzquiz,B,POINT Z (-99.04207 19.50149 0.00000),19.501490,-99.042067
191,Ecatepec,B,POINT Z (-99.03607 19.51513 0.00000),19.515125,-99.036069
192,Olímpica,B,POINT Z (-99.03334 19.52134 0.00000),19.521345,-99.033342
193,Plaza Aragón,B,POINT Z (-99.03018 19.52848 0.00000),19.528476,-99.030185
194,Ciudad Azteca,B,POINT Z (-99.02751 19.53451 0.00000),19.534513,-99.027510

In [31]:
geoData.rename(columns={'lon': 'lng'}, inplace=True)

/var/folders/rb/zftwt_496p14dt4_yp6626_80000gn/T/ipykernel_5871/3055422475.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geoData.rename(columns={'lon': 'lng'}, inplace=True)

In [32]:
geoData.drop(columns=['geometry'], inplace=True, axis=1)

/var/folders/rb/zftwt_496p14dt4_yp6626_80000gn/T/ipykernel_5871/1477193048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geoData.drop(columns=['geometry'], inplace=True, axis=1)

In [ ]:
geoData.to_csv('/Users/rodolfodom/rutas_metro_cdmx/coordinates.csv', index=False)

In [35]:
geoData

                     NOMBRE LINEA        lat        lng
0               Pantitlán-1    01  19.416334 -99.074736
1                  Zaragoza    01  19.411920 -99.082289
2              Gomez Farías    01  19.416478 -99.090210
3    Boulevard Puerto Aéreo    01  19.419942 -99.096259
4                  Balbuena    01  19.423355 -99.102774
..                      ...   ...        ...        ...
190                 Múzquiz     B  19.501490 -99.042067
191                Ecatepec     B  19.515125 -99.036069
192                Olímpica     B  19.521345 -99.033342
193            Plaza Aragón     B  19.528476 -99.030185
194           Ciudad Azteca     B  19.534513 -99.027510

[195 rows x 4 columns]

In [45]:
geodict = geoData[["NOMBRE", "lat", "lng"]].set_index('NOMBRE').T.to_dict('list')
geodict

{'Pantitlán-1': [19.416334085596525, -99.07473572701159],
 'Zaragoza': [19.41192045593743, -99.0822888117768],
 'Gomez Farías': [19.416478456907367, -99.09021039171121],
 'Boulevard Puerto Aéreo': [19.419941964850207, -99.09625873241016],
 'Balbuena': [19.42335533557525, -99.10277436397425],
 'Moctezuma': [19.42685434666967, -99.10979926910476],
 'San Lázaro-1': [19.43005884961391, -99.11426095239393],
 'Candelaria-1': [19.42954014071058, -99.12090955005588],
 'Merced': [19.42548757157406, -99.12502541851761],
 'Pino Suárez-1': [19.425923495107927, -99.13263861199377],
 'Isabel La Católica': [19.42639351179822, -99.13783045646255],
 'Salto del Agua-1': [19.426948189741864, -99.14340629386963],
 'Balderas-1': [19.426997876088905, -99.14948115142849],
 'Cuauhtémoc': [19.4256611110838, -99.15459795134981],
 'Insurgentes': [19.423651800607303, -99.16328887947714],
 'Sevilla': [19.421849915921573, -99.17111907391485],
 'Chapultepec': [19.42074629504737, -99.17641673157046],
 'Juanacatlán': [19.4129516424911, -99.18198382947882],
 'Tacubaya-1': [19.40251380233993, -99.18763652631694],
 'Observatorio': [19.398282375699324, -99.20040474604608],
 'Cuatro Caminos': [19.459593208492073, -99.21584248969683],
 'Panteones': [19.458638560770133, -99.20294912952721],
 'Tacuba-2': [19.459376010718714, -99.18823093441412],
 'Cuitláhuac': [19.457253889739235, -99.18149576791224],
 'Popotla': [19.452909219801555, -99.17549381434115],
 'Colegio Militar': [19.449273554997184, -99.17177923331683],
 'Normal': [19.44455770552456, -99.16727403741045],
 'San Cosme': [19.441904254426483, -99.16066207280677],
 'Revolución': [19.439227179139703, -99.15422782571336],
 'Hidalgo-2': [19.43754674790357, -99.14722340551585],
 'Bellas Artes-2': [19.436377755896043, -99.14161363737124],
 'Allende': [19.43555800327121, -99.13686784023699],
 'Zócalo/Tenochtitlan': [19.432501910975944, -99.13225107327767],
 'Pino Suárez-2': [19.42438471172242, -99.13294182670589],
 'San Antonio Abad': [19.41602164706914, -99.13453987415669],
 'Chabacano-2': [19.40917986927759, -99.1356181172527],
 'Viaducto': [19.400868658018997, -99.13689959248839],
 'Xola': [19.395210509950374, -99.13780817932107],
 'Villa de Cortés': [19.38758177582601, -99.13895916622117],
 'Nativitas': [19.37953276091363, -99.14018788970765],
 'Portales': [19.36992483866799, -99.14157355491439],
 'Ermita-2': [19.361979299764318, -99.14290376152475],
 'General Anaya': [19.353235914861184, -99.14500636295455],
 'Tasqueña': [19.343757098277724, -99.13953277638426],
 'Indios Verdes': [19.495337618645664, -99.11950993825916],
 'Deportivo 18 de Marzo-3': [19.485114151342465, -99.12549791712465],
 'Potrero': [19.47719201148074, -99.13201368299404],
 'La Raza-3': [19.468880133789003, -99.13950623022468],
 'Tlatelolco': [19.45505814280372, -99.1431330841341],
 'Guerrero-3': [19.44472633482843, -99.14519334406981],
 'Hidalgo-3': [19.43738239226258, -99.14678272133695],
 'Juárez': [19.43325034645042, -99.14768330576317],
 'Balderas-3': [19.42648009336695, -99.14906048003867],
 'Niños Héroes/Poder Judicial CDMX': [19.419484310191944, -99.15036426521944],
 'Hospital General': [19.413758753579426, -99.15324536177903],
 'Centro Médico-3': [19.40745314744384, -99.15513468952369],
 'Etiopía/Plaza de la Transparencia': [19.395920531617364, -99.15603141534933],
 'Eugenia': [19.386168518115365, -99.15720459756614],
 'División del Norte': [19.379184435402276, -99.1594791658047],
 'Zapata-3': [19.371191786554387, -99.16451029765572],
 'Coyoacán': [19.361359077350073, -99.17086152734286],
 'Viveros/Derechos Humanos': [19.353459024524685, -99.17600108606379],
 'Miguel Ángel de Quevedo': [19.346251833085887, -99.18075665564406],
 'Copilco': [19.33609927480332, -99.17697359521604],
 'Universidad': [19.324353482894324, -99.17393845558945],
 'Santa Anita-4': [19.402891572700973, -99.12169560425865],
 'Jamaica-4': [19.41091506041839, -99.12174358812516],
 'Fray Servando': [19.421590266885172, -99.12053345294457],
 'Candelaria-4': [19.428764223711585, -99.11942628579929],
 'Morelos-4': [19.439664164892267, -99.11815212250657],
 'Canal del Norte': [19.448945007975038, -99.11613305076399],
 'Consulado-4': [19.45801819921654, -99.11390384847114],
 'Bondojito': [19.46463120134616, -99.11197677850316],
 'Talismán': [19.4743583148983, -99.10801223861532],
 'Martín Carrera-4': [19.4850441446716, -99.10436947745445],
 'Politécnico': [19.50067869865116, -99.14920599260093],
 'Instituto del Petróleo-5': [19.489339309334294, -99.14470974913316],
 'Autobuses del Norte': [19.479070895908745, -99.14065073858234],
 'La Raza-5': [19.469666470585786, -99.13651565050566],
 'Misterios': [19.463112195663303, -99.1302395703195],
 'Valle Gómez': [19.458872139807024, -99.11949099066608],
 'Consulado-5': [19.455135874992198, -99.11353623147821],
 'Eduardo Molina': [19.45139751377978, -99.10529969848143],
 'Aragón': [19.451257588432135, -99.09620515376837],
 'Oceanía-5': [19.44502048612666, -99.08687292405605],
 'Terminal Aérea': [19.434265101782927, -99.08807623735903],
 'Hangares': [19.42434990786488, -99.08813377459762],
 'Pantitlán-5': [19.41510477347348, -99.07432880808665],
 'El Rosario-6': [19.504630143602103, -99.19976981622266],
 'Tezozómoc': [19.494895164082454, -99.19602298699967],
 'UAM Azcapotzalco': [19.49090814292121, -99.18626730878705],
 'Ferrería/Arena Ciudad de México': [19.490673429052162, -99.17415168259645],
 'Norte 45': [19.488671413505823, -99.16299035407454],
 'Vallejo': [19.48984778693472, -99.15600430946392],
 'Instituto del Petróleo-6': [19.491044231378503, -99.14812599880902],
 'Lindavista': [19.488112987791897, -99.135071417918],
 'Deportivo 18 de Marzo-6': [19.483482017273065, -99.12530365865987],
 'La Villa/Basílica': [19.481735808267246, -99.11836926186176],
 'Martín Carrera-6': [19.482938821534876, -99.10747531268115],
 'El Rosario-7': [19.50473787443692, -99.20011586528997],
 'Aquiles Serdán': [19.49064014278564, -99.19535232730325],
 'Camarones': [19.479111542683896, -99.19003757146507],
 'Refinería': [19.46947289434234, -99.1905055272923],
 'Tacuba-7': [19.45823475875799, -99.18716900417594],
 'San Joaquín': [19.44500753968244, -99.19176696408843],
 'Polanco': [19.433553135623136, -99.1909251080933],
 'Auditorio': [19.42576382554425, -99.1920289044083],
 'Constituyentes': [19.411770866194253, -99.19135185542875],
 'Tacubaya-7': [19.40219021827544, -99.18675445901168],
 'San Pedro de Los Pinos': [19.39149177284933, -99.1858059348452],
 'San Antonio': [19.38433767025257, -99.18661355277949],
 'Mixcoac-7': [19.37625650166226, -99.18758241553665],
 'Barranca del Muerto': [19.361501563286584, -99.18926370689458],
 'Garibaldi/Lagunilla-8': [19.444001288500854, -99.13900441274583],
 'Bellas Artes-8': [19.43701291221674, -99.14042072784983],
 'San Juan de Letrán': [19.431580449036026, -99.14125061054364],
 'Salto del Agua-8': [19.427718297697947, -99.14185174647427],
 'Doctores': [19.421545611577116, -99.14318940867469],
 'Obrera': [19.413240376209362, -99.14403796372382],
 'Chabacano-8': [19.410207491075585, -99.13375133526755],
 'La Viga': [19.406709434404345, -99.1262690624544],
 'Santa Anita-8': [19.404123434315892, -99.12065723966121],
 'Coyuya': [19.398302895714913, -99.11348043121852],
 'Iztacalco': [19.38828875746519, -99.11211173088554],
 'Apatlaco': [19.3790998138262, -99.10949014642031],
 'Aculco': [19.37321141061217, -99.1077035934306],
 'Escuadrón 201': [19.3648364116397, -99.10948498429173],
 'Atlalilco-8': [19.35608448367419, -99.10130942995006],
 'Iztapalapa': [19.3578249372119, -99.09344907670477],
 'Cerro de la Estrella': [19.356047872500543, -99.08561607648716],
 'UAM-I': [19.351056166857287, -99.07481741890497],
 'Constitución de 1917': [19.345968405928243, -99.06379884994618],
 'Pantitlán-9': [19.415351168915805, -99.07220534490074],
 'Puebla': [19.40719214298364, -99.08238587967575],
 'Ciudad Deportiva': [19.408433982240478, -99.0912519463776],
 'Velódromo': [19.408539286354042, -99.10315771222376],
 'Mixhiuca': [19.4083714401572, -99.11296847676732],
 'Jamaica-9': [19.40910312787644, -99.12234976018911],
 'Chabacano-9': [19.40851453448194, -99.13397299201031],
 'Lázaro Cárdenas': [19.407218273838726, -99.14462826288435],
 'Centro Médico-9': [19.406561353277546, -99.15602793921477],
 'Chilpancingo': [19.405929858827395, -99.16851936424604],
 'Patriotismo': [19.40610899290181, -99.1789225975409],
 'Tacubaya-9': [19.401460579904057, -99.18776109100934],
 'Tláhuac': [19.286022277290176, -99.0141983243777],
 'Tlaltenco': [19.294353379107935, -99.02403074663107],
 'Zapotitlán': [19.296655586515058, -99.03430689003962],
 'Nopalera': [19.299957304889258, -99.04599286885365],
 'Olivos': [19.304321996002184, -99.05951149501792],
 'Tezonco': [19.306308825509696, -99.06527026370269],
 'Periferico Oriente': [19.317611568465104, -99.07450575078416],
 'Calle 11': [19.320471151871725, -99.08587286436709],
 'Lomas Estrella': [19.322148856344057, -99.09575048151491],
 'San Andres Tomatlán': [19.32814547952075, -99.1045158609058],
 'Culhuacán': [19.336845611079582, -99.10895874517293],
 'Atlalilco-12': [19.352754172814933, -99.10624316535984],
 'Mexicaltzingo': [19.35776253608585, -99.1231432322264],
 'Ermita-12': [19.359823503023833, -99.14163136305437],
 'Eje Central': [19.361341237938568, -99.15142336147862],
 'Parque de los Venados': [19.37065883497745, -99.15871771897177],
 'Zapata-12': [19.37084530155701, -99.165599315594],
 'Hospital 20 de Noviembre': [19.37201337695184, -99.17088446276829],
 'Insurgentes Sur': [19.373553470227108, -99.17825012925253],
 'Mixcoac-12': [19.37569882343627, -99.18673050109385],
 'Pantitlán-A': [19.415297524541934, -99.07192293715731],
 'Agrícola Oriental': [19.404618895931353, -99.06956646430945],
 'Canal de San Juan': [19.39876293119974, -99.05942280066026],
 'Tepalcates': [19.391276494960067, -99.04632939735716],
 'Guelatao': [19.385153887463556, -99.03565960069986],
 'Peñón Viejo': [19.373305051789014, -99.01705483641234],
 'Acatitla': [19.364717390396216, -99.00567271685955],
 'Santa Marta': [19.36030504737167, -98.99517832323626],
 'Los Reyes': [19.35903746198999, -98.97686678250444],
 'La Paz': [19.350561572133337, -98.96093725042675],
 'Buenavista': [19.446185903359645, -99.15235137742634],
 'Guerrero-B': [19.44514483254338, -99.14613872738674],
 'Garibaldi/Lagunilla-B': [19.44388963210198, -99.13786566485716],
 'Lagunilla': [19.443220041827658, -99.13023042923575],
 'Tepito': [19.442789391295424, -99.12406744029855],
 'Morelos-B': [19.439166627281327, -99.11956876702453],
 'San Lázaro-B': [19.432370934586487, -99.11296097266766],
 'Ricardo Flores Magón': [19.43656537337327, -99.10370874117547],
 'Romero Rubio': [19.440835354165493, -99.09420167473102],
 'Oceanía-B': [19.445694826958526, -99.08721732565787],
 'Deportivo Oceanía': [19.451011097259663, -99.07933423067036],
 'Bosque de Aragón': [19.458094772963857, -99.0692886960206],
 'Villa de Aragón': [19.461670791944844, -99.06138196686965],
 'Nezahualcóyotl': [19.472885633631996, -99.05461333650334],
 'Impulsora': [19.485753223001417, -99.0489571600943],
 'Río de los Remedios': [19.490688675585073, -99.04678664175502],
 'Múzquiz': [19.501490328356404, -99.0420671972603],
 'Ecatepec': [19.515125082713773, -99.0360693374375],
 'Olímpica': [19.521344934228452, -99.03334249438895],
 'Plaza Aragón': [19.528475893853724, -99.03018454966082],
 'Ciudad Azteca': [19.53451306511141, -99.0275097173377]}

In [46]:
geodict_str = json.dumps(geodict, ensure_ascii=False)
with open('/Users/rodolfodom/rutas_metro_cdmx/coordinates_tuple.py', 'w', encoding='utf-8') as f:
    f.write(f'coordinates_tuple = {geodict_str}')